import Navbar from '@/components/layout/Navbar';
import '@/app/globals.css';
import { Inter } from 'next/font/google';
import AppProviders from '@/context/app-providers';
import RootStyleRegistry from './emotion';
import { AuthProvider } from '@/context/auth-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const user = {
  name: "Lewis Ndung'u",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RootStyleRegistry>
        <AuthProvider>
          <body className={inter.className}>
            <Navbar user={user} />
            {children}
          </body>
        </AuthProvider>
      </RootStyleRegistry>
    </html>
  );
}
