import Navbar from "@/components/layout/navbar";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import RootStyleRegistry from "../context/mantine-provider";
import NextAuthProvider from "@/context/next-auth-provider";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { NavbarNotifications } from "@/components/notifications/NavbarNotifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RootStyleRegistry>
        <NextAuthProvider>
          <body className={inter.className}>
            {/*@ts-ignore*/}
            <Navbar notificationsIcon={<NavbarNotifications />} />
            {children}
            <TailwindIndicator />
          </body>
        </NextAuthProvider>
      </RootStyleRegistry>
    </html>
  );
}
